# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-12 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapefile',
            name='src_wkt',
            field=models.CharField(max_length=1024),
        ),
    ]
