# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-12 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_auto_20200112_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='geom_multipolygone',
            new_name='geom_multipolygon',
        ),
    ]
